name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: configure
      run: cmake CMakeLists.txt
    - name: make
      run: make
